---
name: Check approval
on:
  pull_request_review:
    types:
      - submitted
permissions: {}
jobs:
  check-approval:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: suzuki-sunsuke/deny-self-approve-action@main
