---
name: Deploy
on:
  push:
    branches:
      - main
permissions: {}
jobs:
  deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
        with:
          aqua_version: v2.44.0
      - run: |
          env=$(ci-info run)
          eval "$env"
          echo "PR_NUMBER=$CI_INFO_PR_NUMBER" >> "$GITHUB_ENV"
      - run: |
          github-comment exec -k deny-self-approve -pr "$PR_NUMBER" -- deny-self-approve --pr "$PR_NUMBER" validate
        env:
          GITHUB_TOKEN: ${{github.token}}
      - run: echo "Deploy"
